version: "3.7"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - dev-network

networks:
  dev-network:
    name: dev-network
    driver: bridge